### ISSUE TITLE
New commands

### ISSUE THREAD

**Issue by sparce** [ttrnecka/imperium#9]
Suggestion for new bot commands:
`!standings`: prints current standings for the ladder competition (needs league/competition from room name, uses data from the `/ladder` endpoint)

`!sponsor`: prints current standings for the tournament sponsor (needs league/competition/sponsor from room name, uses data from the `/matches` endpoint). Will have to implement the sponsors separately, but there should be a fair few that are relatively straightforward to do.

**Comment by ttrnecka** [comment]
Added tournament leaderboard on the webpage
